### ISSUE TITLE
increase network requests body size for debug builds

### ISSUE THREAD

**Issue by NikolayShubenkov** [ingybing/Bugsee#1]
Hello. Is it possible to increase network requests body size?
At least in debug app builds. I use your library for network monitoring too and it is needed in non-production environment.

**Comment by ingybing** [comment]
Hi

I just wrote this as a Xamarin wrapper for bugsee.  They’ve now officially started supporting Xamarin so you need to raise this with the bugsee team. 🙂

**Comment by NikolayShubenkov** [comment]
thanks!
